### ISSUE TITLE
Half Icon Loaded

### ISSUE THREAD

**Issue by CindyMankam** [edwardkcyu/ituni-issues#10] opened 2017-08-07 07:17 UTC
Dont know why i have half icon loaded in the Applications Page
Maybe due to Slow network problem
![20684518_10155742073877427_1766810115_o](https://user-images.githubusercontent.com/30792077/29016086-7c214dc8-7b83-11e7-826f-dedf7a049fc3.jpg)

**Comment by edwardkcyu** [comment] 2017-08-29 06:21
Duplicate of #7

**Closed by edwardkcyu** 2017-08-29 06:21 UTC
