### ISSUE TITLE
Update App with slow network?

### ISSUE THREAD

**Issue by CindyMankam** [edwardkcyu/ituni-issues#42] opened 2017-08-08 03:37 UTC
When i try to update an application with new version, it keeps showing the "Updating application ..." loading mask with more than 10mins. 
![20726891_10155744613552427_998774532_o](https://user-images.githubusercontent.com/30792077/29055231-e8ad2016-7c2d-11e7-8dbb-531f562d03d4.jpg)

**Comment by edwardkcyu** [comment] 2017-08-29 06:21
Duplicate of #7

**Closed by edwardkcyu** 2017-08-29 06:21 UTC
