### ISSUE TITLE
ITUNI Registration page has error at IE browser

### ISSUE THREAD

**Issue by kychoi13** [edwardkcyu/ituni-issues#2] opened 2017-08-07 01:08 UTC
2 script errors are prompted at these scenario:
1. when open http://cmsappsv-corp-eamobile-sit.server.ha.org.hk:14408/eao-ituni-core/1_0_0/registration/ by IE 11 browser
2. when press "Go" after filling in the login id and password.

![regpageiebrowser](https://user-images.githubusercontent.com/30786114/29008835-e9678a2a-7b4f-11e7-97c4-4f0d2c045647.png)

**Comment by edwardkcyu** [comment] 2017-08-08 02:01
Duplicate of #3

**Closed by edwardkcyu** 2017-08-08 02:01 UTC
